force-app/main/default/objects/xDO_Demo_Configuration__c/xDO_Demo_Configuration__c.object-meta.xml
<CustomObject>
    <description>Configurations for a Demo</description>
    <label>Demo Configuration</label>
    <nameField>
        <label>Demo Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Accent_Color_1_HEX_Code__c.field-meta.xml
<CustomField>
    <fullName>xDO_Accent_Color_1_HEX_Code__c</fullName>
    <label>Accent Color 1 HEX Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Accent_Color_2_HEX_Code__c.field-meta.xml
<CustomField>
    <fullName>xDO_Accent_Color_2_HEX_Code__c</fullName>
    <label>Accent Color 2 HEX Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Accent_Color_3_HEX_Code__c.field-meta.xml
<CustomField>
    <fullName>xDO_Accent_Color_3_HEX_Code__c</fullName>
    <label>Accent Color 3 HEX Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Accent_Color_4_HEX_Code__c.field-meta.xml
<CustomField>
    <fullName>xDO_Accent_Color_4_HEX_Code__c</fullName>
    <label>Accent Color 4 HEX Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Active__c.field-meta.xml
<CustomField>
    <fullName>xDO_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Brand_Image__c.field-meta.xml
<CustomField>
    <fullName>xDO_Brand_Image__c</fullName>
    <description>Asset File Unique Name that represents the brand image.</description>
    <inlineHelpText>Asset File Unique Name that represents the brand image.</inlineHelpText>
    <label>Brand Image</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Brand_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>xDO_Brand_Image_URL__c</fullName>
    <label>Brand Image URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Group_Image__c.field-meta.xml
<CustomField>
    <fullName>xDO_Group_Image__c</fullName>
    <description>Asset File Unique Name that represents the group image.</description>
    <inlineHelpText>Asset File Unique Name that represents the group image.</inlineHelpText>
    <label>Group Image</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Group_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>xDO_Group_Image_URL__c</fullName>
    <label>Group Image URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Logo__c.field-meta.xml
<CustomField>
    <fullName>xDO_Logo__c</fullName>
    <description>Asset File Unique Name that represents the logo.</description>
    <inlineHelpText>Asset File Unique Name that represents the logo.</inlineHelpText>
    <label>Logo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>xDO_Logo_URL__c</fullName>
    <label>Logo URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Override_Experience_Cloud_Branding__c.field-meta.xml
<CustomField>
    <fullName>xDO_Override_Experience_Cloud_Branding__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Select this checkbox to override the default Experience Cloud branding and apply custom styles or configurations.</inlineHelpText>
    <label>Override Experience Cloud Branding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Primary_Color_HEX_Code__c.field-meta.xml
<CustomField>
    <fullName>xDO_Primary_Color_HEX_Code__c</fullName>
    <label>Primary Color HEX Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_Secondary_Color_HEX_Code__c.field-meta.xml
<CustomField>
    <fullName>xDO_Secondary_Color_HEX_Code__c</fullName>
    <label>Secondary Color HEX Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_User_Image__c.field-meta.xml
<CustomField>
    <fullName>xDO_User_Image__c</fullName>
    <description>Asset File Unique Name that represents the user image.</description>
    <inlineHelpText>Asset File Unique Name that represents the user image.</inlineHelpText>
    <label>User Image</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_Demo_Configuration__c/fields/xDO_User_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>xDO_User_Image_URL__c</fullName>
    <label>User Image URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/XDO_OverrideSiteDemoController.cls
public without sharing class XDO_OverrideSiteDemoController {
    @AuraEnabled(cacheable=true)
    public static xDO_Demo_Configuration__c getActiveConfig() {
        return [
            SELECT
                Name,
                xDO_Accent_Color_1_HEX_Code__c,
                xDO_Accent_Color_2_HEX_Code__c,
                xDO_Accent_Color_3_HEX_Code__c,
                xDO_Accent_Color_4_HEX_Code__c,
                xDO_Active__c,
                xDO_Brand_Image__c,
                xDO_Brand_Image_URL__c,
                xDO_Group_Image__c,
                xDO_Group_Image_URL__c,
                xDO_Logo__c,
                xDO_Logo_URL__c,
                xDO_Primary_Color_HEX_Code__c,
                xDO_Secondary_Color_HEX_Code__c,
                xDO_User_Image__c,
                xDO_User_Image_URL__c
            FROM xDO_Demo_Configuration__c
            WHERE xDO_Active__c = true AND xDO_Override_Experience_Cloud_Branding__c = true
            LIMIT 1
        ];
    }
}